export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"主页","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-2d0a870d","/en/",{"t":"项目主页","i":"home"},["/en/index.html","/en/README.md"]],
  ["v-367b840a","/en/slides.html",{"t":"幻灯片页","i":"slides"},["/en/slides","/en/slides.md"]],
  ["v-d0736a32","/usage/",{"t":"如何使用","i":"discover"},["/usage/index.html","/usage/README.md"]],
  ["v-0cd57e8c","/usage/linux.html",{"t":"Linux","i":"linux"},["/usage/linux","/usage/linux.md"]],
  ["v-bb3e2926","/usage/macos.html",{"t":"MacOS","i":"computer"},["/usage/macos","/usage/macos.md"]],
  ["v-272be09d","/usage/windows.html",{"t":"Windows","i":"windows"},["/usage/windows","/usage/windows.md"]],
  ["v-7446a652","/faq/",{"t":"常见问题","i":"discover"},["/faq/index.html","/faq/README.md"]],
  ["v-e6412400","/en/guide/",{"t":"指南","i":"creative"},["/en/guide/index.html","/en/guide/README.md"]],
  ["v-395cd082","/en/demo/",{"t":"主要功能与配置演示","i":"discover"},["/en/demo/index.html","/en/demo/README.md"]],
  ["v-70eda030","/en/demo/disable.html",{"t":"布局与功能禁用","i":"config"},["/en/demo/disable","/en/demo/disable.md"]],
  ["v-3777b6d3","/en/demo/encrypt.html",{"t":"密码加密的文章","i":"lock"},["/en/demo/encrypt","/en/demo/encrypt.md"]],
  ["v-4a2a37eb","/en/demo/markdown.html",{"t":"Markdown 展示","i":"markdown"},["/en/demo/markdown","/en/demo/markdown.md"]],
  ["v-0e4acecb","/en/demo/page.html",{"t":"页面配置","i":"page"},["/en/demo/page","/en/demo/page.md"]],
  ["v-13a6747c","/en/guide/bar/",{"t":"Bar 功能","i":"creative"},["/en/guide/bar/index.html","/en/guide/bar/README.md"]],
  ["v-f91f53cc","/en/guide/bar/baz.html",{"t":"Baz","i":"info"},["/en/guide/bar/baz","/en/guide/bar/baz.md"]],
  ["v-13a87a29","/en/guide/foo/",{"t":"Foo 功能","i":"config"},["/en/guide/foo/index.html","/en/guide/foo/README.md"]],
  ["v-663a5418","/en/guide/foo/ray.html",{"t":"Ray","i":"config"},["/en/guide/foo/ray","/en/guide/foo/ray.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
