export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"主页","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-d0736a32","/usage/",{"t":"如何使用","i":"discover"},["/usage/index.html","/usage/README.md"]],
  ["v-0cd57e8c","/usage/linux.html",{"t":"Linux","i":"linux"},["/usage/linux","/usage/linux.md"]],
  ["v-bb3e2926","/usage/macos.html",{"t":"MacOS","i":"computer"},["/usage/macos","/usage/macos.md"]],
  ["v-272be09d","/usage/windows.html",{"t":"Windows","i":"windows"},["/usage/windows","/usage/windows.md"]],
  ["v-2d0ad528","/zh/",{"t":"项目主页","i":"home"},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"t":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-2b64e284","/zh/demo/",{"t":"主要功能与配置演示","i":"discover"},["/zh/demo/index.html","/zh/demo/README.md"]],
  ["v-c1942916","/zh/demo/disable.html",{"t":"布局与功能禁用","i":"config"},["/zh/demo/disable","/zh/demo/disable.md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"t":"密码加密的文章","i":"lock"},["/zh/demo/encrypt","/zh/demo/encrypt.md"]],
  ["v-36295574","/zh/demo/markdown.html",{"t":"Markdown 展示","i":"markdown"},["/zh/demo/markdown","/zh/demo/markdown.md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"t":"页面配置","i":"page"},["/zh/demo/page","/zh/demo/page.md"]],
  ["v-47357bdb","/zh/guide/",{"t":"指南","i":"creative"},["/zh/guide/index.html","/zh/guide/README.md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"t":"Bar 功能","i":"creative"},["/zh/guide/bar/index.html","/zh/guide/bar/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"t":"Baz","i":"info"},["/zh/guide/bar/baz","/zh/guide/bar/baz.md"]],
  ["v-763e2284","/zh/guide/foo/",{"t":"Foo 功能","i":"config"},["/zh/guide/foo/index.html","/zh/guide/foo/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"t":"Ray","i":"config"},["/zh/guide/foo/ray","/zh/guide/foo/ray.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
